
package br.com.fiap.governo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceNFService", targetNamespace = "http://ws.governo.com.br/", wsdlLocation = "http://fiapgoverno.brazilsouth.cloudapp.azure.com:8080/Governo/WebServiceNF?wsdl")
public class WebServiceNFService
    extends Service
{

    private final static URL WEBSERVICENFSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICENFSERVICE_EXCEPTION;
    private final static QName WEBSERVICENFSERVICE_QNAME = new QName("http://ws.governo.com.br/", "WebServiceNFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fiapgoverno.brazilsouth.cloudapp.azure.com:8080/Governo/WebServiceNF?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICENFSERVICE_WSDL_LOCATION = url;
        WEBSERVICENFSERVICE_EXCEPTION = e;
    }

    public WebServiceNFService() {
        super(__getWsdlLocation(), WEBSERVICENFSERVICE_QNAME);
    }

    public WebServiceNFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICENFSERVICE_QNAME, features);
    }

    public WebServiceNFService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICENFSERVICE_QNAME);
    }

    public WebServiceNFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICENFSERVICE_QNAME, features);
    }

    public WebServiceNFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceNFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceNF
     */
    @WebEndpoint(name = "WebServiceNFPort")
    public WebServiceNF getWebServiceNFPort() {
        return super.getPort(new QName("http://ws.governo.com.br/", "WebServiceNFPort"), WebServiceNF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceNF
     */
    @WebEndpoint(name = "WebServiceNFPort")
    public WebServiceNF getWebServiceNFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.governo.com.br/", "WebServiceNFPort"), WebServiceNF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICENFSERVICE_EXCEPTION!= null) {
            throw WEBSERVICENFSERVICE_EXCEPTION;
        }
        return WEBSERVICENFSERVICE_WSDL_LOCATION;
    }

}
